# Generated by Django 3.1.3 on 2021-01-08 07:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_name', models.CharField(blank=True, max_length=60, null=True)),
                ('main_category_imageUpload', models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload/images/')),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, max_length=60, null=True)),
                ('banner_imageUpload', models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload/images/')),
                ('banner_type', models.CharField(choices=[('0', 'Main')], default='1', max_length=1)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=60, null=True)),
                ('food_category', models.CharField(blank=True, max_length=60, null=True)),
                ('hotel_address', models.CharField(blank=True, max_length=60, null=True)),
                ('hotel_open_time', models.TimeField(blank=True, null=True)),
                ('hotel_close_time', models.TimeField(blank=True, null=True)),
                ('hotel_discount', models.CharField(blank=True, max_length=60, null=True)),
                ('hotel_amount', models.CharField(blank=True, max_length=60, null=True)),
                ('hotel_contact', models.CharField(blank=True, max_length=60, null=True)),
                ('hotel_total_seats', models.CharField(blank=True, max_length=60, null=True)),
                ('hotel_rating', models.CharField(blank=True, max_length=60, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, max_length=60, null=True)),
                ('restaurant_username', models.CharField(blank=True, max_length=60, null=True)),
                ('restaurant_password', models.CharField(blank=True, max_length=60, null=True)),
                ('restaurant_imageUpload', models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload/images/')),
                ('restaurant_address', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=60, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=60, null=True, unique=True)),
                ('user_password', models.CharField(blank=True, max_length=60, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
                ('user_gender', models.CharField(blank=True, max_length=60, null=True)),
                ('user_social_id', models.CharField(blank=True, max_length=60, null=True)),
                ('user_status', models.CharField(choices=[('0', 'Suspended'), ('1', 'Live')], default='1', max_length=1)),
                ('user_dob', models.CharField(blank=True, max_length=60, null=True)),
                ('user_address', models.CharField(blank=True, max_length=200, null=True)),
                ('user_image', models.CharField(blank=True, max_length=300, null=True)),
                ('user_imageUpload', models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload/images/')),
                ('login_type', models.CharField(blank=True, max_length=60, null=True)),
                ('forgot_pass_token', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=60, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=60, null=True)),
                ('paid_amount', models.CharField(blank=True, max_length=60, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID', to='firstapi.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='MyFoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item_name', models.CharField(blank=True, max_length=60, null=True)),
                ('food_item_imageUpload', models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload/images/')),
                ('food_item_discount', models.CharField(blank=True, max_length=60, null=True)),
                ('food_item_amount', models.CharField(blank=True, max_length=60, null=True)),
                ('food_item_rating', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'INACIVE')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainfoodcategory', to='firstapi.maincategory')),
                ('restaurant_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantdetail', to='firstapi.myrestaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_items', models.CharField(blank=True, default='1', max_length=60, null=True)),
                ('total_price', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('my_foods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfood', to='firstapi.myfooditem')),
                ('my_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to='firstapi.myuser')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfood', to='firstapi.myrestaurant')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_imageUpload', models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload/images/')),
                ('my_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myhotel', to='firstapi.myhotel')),
            ],
        ),
    ]
