# Generated by Django 3.0.8 on 2020-09-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_firebasenotification_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirebaseNotification',
        ),
    ]
